// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk28hwDunbeWJ3U99ivweiIZlrQYpxdKc',
    appId: '1:1093547452655:web:d94cf95c0594119baed31a',
    messagingSenderId: '1093547452655',
    projectId: 'flutter-ecommerce-app-b39f5',
    authDomain: 'flutter-ecommerce-app-b39f5.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-b39f5.appspot.com',
    measurementId: 'G-VPRGC38QGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvKUN7E68zyIlq1hd0pcknQsB2Eei6Dw',
    appId: '1:1093547452655:android:95a4e09705cf52acaed31a',
    messagingSenderId: '1093547452655',
    projectId: 'flutter-ecommerce-app-b39f5',
    storageBucket: 'flutter-ecommerce-app-b39f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqunkljT93X4I1wLmjrHlmaAyyzcc3Kvw',
    appId: '1:1093547452655:ios:1e2833908850e4d3aed31a',
    messagingSenderId: '1093547452655',
    projectId: 'flutter-ecommerce-app-b39f5',
    storageBucket: 'flutter-ecommerce-app-b39f5.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqunkljT93X4I1wLmjrHlmaAyyzcc3Kvw',
    appId: '1:1093547452655:ios:0f8a829eb963e5a3aed31a',
    messagingSenderId: '1093547452655',
    projectId: 'flutter-ecommerce-app-b39f5',
    storageBucket: 'flutter-ecommerce-app-b39f5.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp.RunnerTests',
  );
}
